"""Generated model names from all providers.

Auto-generated by scripts/generate_model_names.py - do not edit manually.
Total providers: 13
"""

from __future__ import annotations


from .mistral import MistralModels
from .groq import GroqModels
from .anthropic import AnthropicModels
from .openai import OpenaiModels
from .gemini import GeminiModels
from .cerebras import CerebrasModels
from .deepseek import DeepseekModels
from .xai import XaiModels
from .comet import CometModels
from .ollama import OllamaModels
from .vercel_gateway import Vercel_GatewayModels
from .moonshotai import MoonshotaiModels
from .zai import ZaiModels

# Union of all provider model types
ModelName = (
    MistralModels |
    GroqModels |
    AnthropicModels |
    OpenaiModels |
    GeminiModels |
    CerebrasModels |
    DeepseekModels |
    XaiModels |
    CometModels |
    OllamaModels |
    Vercel_GatewayModels |
    MoonshotaiModels |
    ZaiModels
)

__all__ = [
    "AnthropicModels",
    "CerebrasModels",
    "CometModels",
    "DeepseekModels",
    "GeminiModels",
    "GroqModels",
    "MistralModels",
    "ModelName",
    "MoonshotaiModels",
    "OllamaModels",
    "OpenaiModels",
    "Vercel_GatewayModels",
    "XaiModels",
    "ZaiModels",
]
