"""Generated model names for cerebras provider.

Auto-generated by scripts/generate_model_names.py - do not edit manually.
Total models: 1
"""

from __future__ import annotations

from typing import Literal


# Fully-qualified model IDs (provider:model format)
CerebrasModelId = Literal[
    "cerebras:zai-glm-4.7",
]

# Model names without provider prefix
CerebrasModelName = Literal[
    "zai-glm-4.7",
]

__all__ = ["CerebrasModelId", "CerebrasModelName"]
