"""Generated model names for cerebras provider.

Auto-generated by scripts/generate_model_names.py - do not edit manually.
Total models: 2
"""

from __future__ import annotations

from typing import Literal


# Fully-qualified model IDs (provider:model format)
CerebrasModelId = Literal[
    "cerebras:gpt-oss-120b",
    "cerebras:zai-glm-4.7",
]

# Model names without provider prefix
CerebrasModelName = Literal[
    "gpt-oss-120b",
    "zai-glm-4.7",
]

__all__ = ["CerebrasModelId", "CerebrasModelName"]
