"""Generated model names for xai provider.

Auto-generated by scripts/generate_model_names.py - do not edit manually.
Total models: 5
"""

from __future__ import annotations

from typing import Literal


# Fully-qualified model IDs (provider:model format)
XaiModelId = Literal[
    "xai:grok-4-1-fast-non-reasoning",
    "xai:grok-4-1-fast-reasoning",
    "xai:grok-4-fast-non-reasoning",
    "xai:grok-4-fast-reasoning",
    "xai:grok-code-fast-1",
]

# Model names without provider prefix
XaiModelName = Literal[
    "grok-4-1-fast-non-reasoning",
    "grok-4-1-fast-reasoning",
    "grok-4-fast-non-reasoning",
    "grok-4-fast-reasoning",
    "grok-code-fast-1",
]

__all__ = ["XaiModelId", "XaiModelName"]
