"""Script to fetch models from all providers and generate separate files per provider."""

from __future__ import annotations

from collections import defaultdict
import logging
from pathlib import Path

from tokonomics.model_discovery import get_all_models_sync


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def generate_provider_file(provider: str, model_ids: list[str], output_dir: Path) -> str:
    """Generate a Python file for a specific provider.

    Args:
        provider: Provider name
        model_ids: List of model IDs for this provider
        output_dir: Output directory path

    Returns:
        The type name for this provider
    """
    # Create valid Python identifier from provider name
    type_name = f"{provider.replace('-', '_').replace('.', '_').title()}Models"
    filename = f"{provider.replace('-', '_').replace('.', '_').lower()}.py"

    formatted_ids = ",\n    ".join(f'"{mid}"' for mid in model_ids)

    content = f'''"""Generated model names for {provider} provider.

Auto-generated by scripts/generate_model_names.py - do not edit manually.
Total models: {len(model_ids)}
"""

from __future__ import annotations

from typing import Literal


{type_name} = Literal[
    {formatted_ids},
]

__all__ = ["{type_name}"]
'''

    file_path = output_dir / filename
    with file_path.open("w") as f:
        f.write(content)

    logger.info("Generated %s with %d models", file_path, len(model_ids))
    return type_name


def generate_init_file(provider_types: dict[str, str], output_dir: Path) -> None:
    """Generate __init__.py with union of all provider types.

    Args:
        provider_types: Mapping of provider name to type name
        output_dir: Output directory path
    """
    imports = []
    type_names = []

    # Sort providers to ensure consistent import order
    for provider, type_name in sorted(provider_types.items()):
        module_name = provider.replace("-", "_").replace(".", "_").lower()
        imports.append(f"from .{module_name} import {type_name}")
        type_names.append(type_name)

    imports_str = "\n".join(imports)
    # Fix formatting to put pipe at beginning of line (except first)
    if type_names:
        formatted_types = [type_names[0]]  # First type without pipe
        for type_name in type_names[1:]:
            formatted_types.append(f"| {type_name}")
        union_types = "\n    ".join(formatted_types)
    else:
        union_types = ""
    all_exports = [f'"{name}"' for name in type_names] + ['"ModelName"']
    all_exports.sort()  # Sort alphabetically
    all_exports_str = ",\n    ".join(all_exports)

    content = f'''"""Generated model names from all providers.

Auto-generated by scripts/generate_model_names.py - do not edit manually.
Total providers: {len(provider_types)}
"""

from __future__ import annotations


{imports_str}

# Union of all provider model types
ModelName = (
    {union_types}
)

__all__ = [
    {all_exports_str},
]
'''

    init_path = output_dir / "__init__.py"
    with init_path.open("w") as f:
        f.write(content)

    logger.info("Generated %s with union of %d providers", init_path, len(provider_types))


def main() -> None:
    """Generate separate Python files for each provider with model names."""
    logger.info("Fetching models from all available providers...")

    # Fetch models with limited concurrency to avoid overwhelming APIs
    models = get_all_models_sync(max_workers=3)

    if not models:
        logger.error("No models found")
        return

    # Group models by provider
    models_by_provider: dict[str, set[str]] = defaultdict(set)
    for model in models:
        models_by_provider[model.provider].add(model.pydantic_ai_id)

    # Sort model IDs for each provider
    sorted_models_by_provider = {
        provider: sorted(model_ids) for provider, model_ids in models_by_provider.items()
    }

    total_models = sum(len(ids) for ids in sorted_models_by_provider.values())
    logger.info(
        "Found %d unique models from %d providers",
        total_models,
        len(sorted_models_by_provider),
    )

    # Create output directory
    output_dir = Path("src/tokonomics/model_names")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate file for each provider
    provider_types = {}
    for provider, model_ids in sorted_models_by_provider.items():
        type_name = generate_provider_file(provider, model_ids, output_dir)
        provider_types[provider] = type_name

    # Generate __init__.py with union type
    generate_init_file(provider_types, output_dir)

    logger.info("Generated model names package at %s", output_dir)


if __name__ == "__main__":
    main()
